### ISSUE TITLE
Rework routing and URL paths

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes#362]
Here's the plan so far, as discussed with @yochannah.

## URL paths
- Gene
old: /reportpage/humanmine/Gene/1208821
new: /humanmine/report/Gene/1208821
- Organism
old: /reportpage/humanmine/Organism/1208821
new: /humanmine/report/Organism/1208821
- Lists
old: /results/PL_Pax6_Targets
new: /humanmine/list/PL_Pax6_Targets
- Query
old: /results/Custom Built Query
new: /humanmine/list/Custom Built Query
- Search
old: /search
new: /humanmine/search?key="gata1"

## Goals
- [x] Rename reportpage path
- [x] Query string including keyword for *search* path
- [x] Replace *results* path with *list*
- [x] If a list is not in the history, automatically query for it (such as the case when directly opening path `/humanmine/list/PL_Pax6_Targets`) #66
- [x] Make sure report page deep links work from a cold start in a different mine #78
- [x] Deep linking of mines (try to have the mine namespace optional in the URL path, but fallback to specifying `default` if this isn't practical) #352
- [x] Replace secretary+accountant with reitit for reverse-routing (so we can easily rename routes)
- [x] Use anchor elements and href (to allow *open in new window*) #90
- [x] Use HTML5 history API instead of hash history
- [x] Make sure back button works with the new solution
